- name: install updates
  gather_facts: no
  become: true
  hosts: all
  tasks:
          - name: Updating host using apt
            apt:
                    update_cache: yes
                    upgrade: dist
          - name: Clean unwanted olderstuff
            apt:
                    autoremove: yes
                    purge: yes
